name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "!**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-amd64:
    uses: ./.github/workflows/tests.yaml
    with:
      arch: amd64
      runner: ubuntu-24.04

  test-amd64-passed:
    needs: [test-amd64]
    if: ${{ !cancelled() }}  # run even if tests are skipped or failed
    runs-on: ubuntu-latest
    steps:
      - name: Fail if any tests failed
        if: ${{ needs.test-amd64.result != 'success' }}
        run: |
          echo '${{ toJSON(needs) }}' | jq  # logging
          exit 1

  test-arch:  # test alternative architectures
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: ppc64le  # note: ppc64le for arch, ppc64el in runner name
            runner: self-hosted-linux-ppc64el-noble-edge
          - arch: s390x
            runner: self-hosted-linux-s390x-noble-edge
    uses: ./.github/workflows/tests.yaml
    with:
      runner: ${{ matrix.runner }}
      arch: ${{ matrix.arch }}
