name: Test on alternative architectures

on:
  workflow_call:  # FIXME: remove this trigger before merging
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: ppc64le  # note: ppc64le for arch, ppc64el in runner name
            runner: self-hosted-linux-ppc64el-noble-edge
          - arch: s390x
            runner: self-hosted-linux-s390x-noble-edge
    uses: ./.github/workflows/_test-on-arch.yaml
    with:
      arch: ${{ matrix.arch }}
      runner: ${{ matrix.runner }}
